### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by F4u5t** [sverrirs/SkypeNet#2]
im fairly new to c#, could you show me how to use this?

**Comment by estuardolh** [comment]
See the SkypeNet.App folder for examples on how to use these classes.

**Comment by F4u5t** [comment]
I saw that but I need something a bit more. any examples in WPF?

**Comment by sverrirs** [comment]
Unfortunately there are is no WPF font-end coding example for this project.  However there is a WinForms application that you can use as a reference under https://github.com/sverrirs/SkypeNet/tree/master/SkypeNet.App
